### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by dengnan123** [owl1n/nest-queue#5]
**Here is some of my information**

> **error message**

```
(node:98239) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at instanceWrappers.map (/Users/dany/Desktop/工作/dfocus-remind-backend-system/node_modules/nest-queue/dist/queue.provider.js:45:46)
    at Array.map (<anonymous>)
    at QueueProvider.getEventConsumers (/Users/dany/Desktop/工作/dfocus-remind-backend-system/node_modules/nest-queue/dist/queue.provider.js:44:14)
    at QueueModule.onModuleInit (/Users/dany/Desktop/工作/dfocus-remind-backend-system/node_modules/nest-queue/dist/queue.module.js:34:41)
    at Object.callModuleInitHook (/Users/dany/Desktop/工作/dfocus-remind-backend-system/node_modules/@nestjs/core/hooks/on-module-init.hook.js:42:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:98239) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:98239) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> **app.module.ts**
```
import { Module } from '@nestjs/common';
import { QueueModule } from 'nest-queue';
// import { AppController } from './app.controller';
// import { AppService } from './app.service';

@Module({
  imports: [
    QueueModule.forRoot({
      name: 'meeting',
      connection: {
        redis: {
          port: 6379,
        },
      },
    }),
  ],
  // controllers: [AppController],
  // providers: [AppService],
})
export class AppModule {}

```

> **pkg**
```
    "@nestjs/bull": "0.0.1-beta.4",
    "@nestjs/common": "^6.0.0",
    "@nestjs/core": "^6.0.0",
    "@nestjs/platform-express": "^6.0.0",
    "bull": "^3.12.1",
    "nest-queue": "^1.0.3",
```

**Please help me see，thanks**

**Comment by oak-c** [comment]
Same question.
<img width="813" alt="image" src="https://user-images.githubusercontent.com/50687915/105277747-f9fe6c00-5bde-11eb-84e1-205c1be7dc30.png">
